---
abstract: 'Utilities to read and manipulate patches and CVS'
author:
  - 'John Keiser <john@johnkeiser.com>'
build_requires:
  Data::Dumper: 0
  File::Find: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PatchReader
provides:
  PatchReader:
    file: lib/PatchReader.pm
    version: 0.9.7
  PatchReader::AddCVSContext:
    file: lib/PatchReader/AddCVSContext.pm
  PatchReader::Base:
    file: lib/PatchReader/Base.pm
  PatchReader::CVSClient:
    file: lib/PatchReader/CVSClient.pm
  PatchReader::DiffPrinter::raw:
    file: lib/PatchReader/DiffPrinter/raw.pm
  PatchReader::DiffPrinter::template:
    file: lib/PatchReader/DiffPrinter/template.pm
  PatchReader::FilterPatch:
    file: lib/PatchReader/FilterPatch.pm
  PatchReader::FixPatchRoot:
    file: lib/PatchReader/FixPatchRoot.pm
  PatchReader::NarrowPatch:
    file: lib/PatchReader/NarrowPatch.pm
  PatchReader::PatchInfoGrabber:
    file: lib/PatchReader/PatchInfoGrabber.pm
  PatchReader::Raw:
    file: lib/PatchReader/Raw.pm
requires:
  Cwd: 2
  File::Temp: 0.05
resources:
  license: http://opensource.org/licenses/artistic-license.php
  repository: https://github.com/tmannerm/PatchReader/
version: 0.9.7
