# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PatchReader
version:      0.9.6
version_from: lib/PatchReader.pm
installdirs:  site
requires:
    Cwd:                           2
    File::Temp:                    0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
